export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_ERROR = "GET_ITEMS_ERROR";

export const GET_RECIPE_ITEMS_REQUEST = "GET_RECIPE_ITEMS_REQUEST";
export const GET_RECIPE_ITEMS_SUCCESS = "GET_RECIPE_ITEMS_SUCCESS";
export const GET_RECIPE_ITEMS_ERROR = "GET_RECIPE_ITEMS_ERROR";

export const GET_RANDOM_RECIPE_ITEMS_ERROR = "GET_RANDOM_RECIPE_ITEMS_ERROR";
export const GET_RANDOM_RECIPE_ITEMS_REQUEST =
  "GET_RANDOM_RECIPE_ITEMS_REQUEST";
export const GET_RANDOM_RECIPE_ITEMS_SUCCESS =
  "GET_RANDOM_RECIPE_ITEMS_SUCCESS";

export const GET_SAVED_RECIPE_ITEMS_REQUEST = "GET_SAVED_RECIPE_ITEMS_REQUEST";
export const GET_SAVED_RECIPE_ITEMS_SUCCESS = "GET_SAVED_RECIPE_ITEMS_SUCCESS";
export const GET_SAVED_RECIPE_ITEMS_ERROR = "GET_SAVED_RECIPE_ITEMS_ERROR";

export const ADD_SAVED_RECIPE_ITEMS_REQUEST = "ADD_SAVED_RECIPE_ITEMS_REQUEST";
export const ADD_SAVED_RECIPE_ITEMS_SUCCESS = "ADD_SAVED_RECIPE_ITEMS_SUCCESS";
export const ADD_SAVED_RECIPE_ITEMS_ERROR = "ADD_SAVED_RECIPE_ITEMS_ERROR";

export const ADD_USER_DATA_SIGNUP = "ADD_USER_DATA_SIGNUP";
export const ADD_USER_DATA_SIGNUP_FAIL = "ADD_USER_DATA_SIGNUP_FAIL";
export const ADD_USER_DATA_LOGIN = "ADD_USER_DATA_LOGIN";
export const ADD_USER_DATA_LOGIN_FAIL = "ADD_USER_DATA_LOGIN_FAIL";

export const ADD_LOGIN_STATUS = "ADD_LOGIN_STATUS";
